# -*- coding: utf-8 -*-
"""cv Lab6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lPdkJV8eRjb5blxMMj808HHknjukL7YG
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
img = cv2.imread("/content/21.jpg", 0)
plt.figure(figsize=(12, 8))
plt.subplot(3, 3, 1)
plt.imshow(img, cmap="gray")
plt.title("Original Image")
plt.axis("off")
for i in range(8):
    bit_plane = (img >> i) & 1
    bit_plane = bit_plane * 255
    plt.subplot(3, 3, i + 2)
    plt.imshow(bit_plane, cmap="gray")
    plt.title("Bit Plane " + str(i))
    plt.axis("off")
plt.tight_layout()
plt.show()